defaults: &defaults
  rendezvous:

    # For amil body
    app_host: <%= ENV['RV_RENDEZVOUS_APP_HOST'] %>

  permited_login_domain: <%= ENV['RV_PERMITTED_LOGIN_DOMAIN'] %>

  # optional
  google_analytics: <%= ENV['RV_GOOGLE_ANALYTICS_ID'] %>

  # optional
  enable_pdf_uploading: <%= ENV['RV_PDF_UPLOADING'].present? %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

