defaults: &defaults
  rendezvous:

    # For amil body
    app_host: <%= ENV['RV_RENDEZVOUS_APP_HOST'] %>

  permited_login_domain: <%= ENV['RV_PERMITTED_LOGIN_DOMAIN'] %>

  # For file upload
  s3:
    access_key_id: <%= ENV['RV_S3_ASSESS_KEY_ID'] %>
    secret_access_key: <%= ENV['RV_S3_SECRET_ACCESS_KEY'] %>
    bucket_name: <%= ENV['RV_S3_BACKET_NAME'] %>

  # optional
  google_analytics: <%= ENV['RV_GOOGLE_ANALYTICS_ID'] %>

  # optional
  enable_pdf_uploading: <%= ENV['RV_PDF_UPLOADING'].present? %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

